export const groupsGuide = {
  title: 'Nhóm chức năng — học theo từng cụm tính năng',
  sections: [
    {
      id: 'tai-khoan',
      title: 'Tài khoản',
      icon: 'User',
      steps: [
        {
          id: 'G01', title: 'Đăng nhập',
          purpose: 'Vào hệ thống để tạo và theo dõi đề xuất của bạn.',
          audience: 'Tất cả người dùng đã có tài khoản.',
          prereq: 'Có email + mật khẩu do quản trị cấp hoặc tự đăng ký.',
          substeps: ['Mở trang Đăng nhập.', 'Nhập email và mật khẩu rồi bấm nút Đăng nhập (ô khoanh số 1 trong ảnh).'],
          expected: 'Vào trang Bản đồ; tên bạn hiện ở góc màn hình.',
          errors: ['Sai email/mật khẩu: kiểm tra lại, chú ý Caps Lock.', 'Tài khoản bị khóa: liên hệ quản trị.'],
          image: '/help/user/a01_dang-nhap.jpg', route: '/login', tags: ['đăng nhập', 'login'], related: ['G02', 'G05'],
        },
        {
          id: 'G02', title: 'Đăng ký',
          purpose: 'Tạo tài khoản mới khi bạn chưa có.',
          audience: 'Người mới, chưa có tài khoản.',
          substeps: ['Mở trang Đăng ký.', 'Điền họ tên, email, số điện thoại, mật khẩu rồi bấm Đăng ký.'],
          expected: 'Đăng nhập được ngay với tài khoản vừa tạo (vai trò mặc định CTV).',
          errors: ['Email đã tồn tại: dùng email khác hoặc Đăng nhập.', 'Mật khẩu quá ngắn: đặt dài hơn theo gợi ý trên form.'],
          image: '/help/user/a02_dang-ky.jpg', route: '/register', tags: ['đăng ký', 'register'], related: ['G01'],
        },
        {
          id: 'G03', title: 'Đăng xuất',
          purpose: 'Thoát tài khoản khi dùng chung máy hoặc xong việc.',
          substeps: ['Trên máy tính: bấm nút Đăng xuất ở thanh header phía trên.', 'Trên điện thoại: mở menu (3 gạch) rồi bấm Đăng xuất ở cuối.'],
          expected: 'Về trang Đăng nhập; người khác mở máy không vào được tài khoản bạn.',
          image: '/help/user/g03_dang-xuat.jpg', route: '/map', tags: ['đăng xuất', 'logout'],
        },
        {
          id: 'G04', title: 'Hồ sơ cá nhân',
          purpose: 'Xem và cập nhật thông tin của bạn (tên, SĐT...).',
          substeps: ['Vào trang Hồ sơ từ menu.', 'Sửa thông tin rồi bấm Lưu.'],
          expected: 'Thông tin mới hiện ngay trên trang và góc màn hình.',
          image: '/help/user/a03_ho-so.jpg', route: '/profile', tags: ['hồ sơ', 'profile'], related: ['G05'],
        },
        {
          id: 'G05', title: 'Đổi mật khẩu',
          purpose: 'Đổi mật khẩu định kỳ hoặc khi nghi lộ.',
          audience: 'Tất cả người dùng.',
          prereq: 'Đang đăng nhập; nhớ mật khẩu cũ.',
          substeps: ['Vào Hồ sơ, tìm phần đổi mật khẩu.', 'Nhập mật khẩu cũ + mật khẩu mới 2 lần rồi lưu.'],
          expected: 'Đổi xong vẫn ở trong hệ thống; các phiên đăng nhập cũ trên máy khác bị đăng xuất.',
          errors: ['Nhập sai mật khẩu cũ: thử lại cẩn thận.', 'Quên mật khẩu cũ: liên hệ quản trị để đặt lại.'],
          image: '/help/user/g05_doi-mat-khau.jpg', route: '/profile', tags: ['mật khẩu', 'password'], related: ['G04'],
        },
      ],
    },
    {
      id: 'ban-do',
      title: 'Bản đồ & xem dữ liệu',
      icon: 'Map',
      steps: [
        {
          id: 'G06', title: 'Xem marker & chú thích',
          purpose: 'Nhìn tổng thể trạm và đề xuất trên bản đồ, đoán màu là biết tình trạng.',
          substeps: ['Mở trang Bản đồ.', 'Mỗi chấm (marker) là một trạm hoặc đề xuất; bấm vào chấm để xem tóm tắt.', 'Mở bảng Chú thích để tra màu (xem thêm S03).'],
          expected: 'Bạn đọc được bản đồ: đâu là trạm hoạt động, đâu là đề xuất chờ duyệt.',
          errors: ['Bản đồ trắng kèm cảnh báo tile: mạng yếu hoặc nguồn bản đồ lỗi — thử đổi nền khác (G08).'],
          image: '/help/user/a04-ban-do.jpg', route: '/map', tags: ['marker', 'bản đồ'], related: ['S03', 'G07'],
        },
        {
          id: 'G07', title: 'Bộ lọc bản đồ',
          purpose: 'Bớt chấm trên bản đồ để chỉ xem cái mình cần (vd chỉ đề xuất của tôi, chỉ Cấp 1).',
          substeps: ['Bấm nút Bộ lọc bản đồ (ô khoanh số 1 trong ảnh).', 'Chọn phạm vi Của tôi hoặc Tất cả.', 'Tích/bỏ tích Trạm, Đề xuất; chọn trạng thái và Cấp 1/Cấp 2 cần xem.'],
          expected: 'Bản đồ chỉ còn marker đúng điều kiện; đổi lọc là cập nhật ngay.',
          image: '/help/user/a05-bo-loc.jpg', route: '/map', tags: ['bộ lọc', 'filter'], related: ['G06'],
        },
        {
          id: 'G08', title: 'Chuyển nền bản đồ',
          purpose: 'Đổi kiểu nền cho dễ nhìn (đường phố để xem tên đường, vệ tinh để xem địa hình thật).',
          substeps: ['Bấm nút Chuyển layer.', 'Chọn 1 trong 4: Đường phố / Vệ tinh / Vệ tinh + nhãn / Địa hình.'],
          expected: 'Nền đổi ngay, vị trí marker giữ nguyên.',
          image: '/help/user/a06-chuyen-layer.jpg', route: '/map', tags: ['layer', 'vệ tinh'], related: ['G09', 'G10'],
        },
        {
          id: 'G09', title: 'Nhãn hành chính mới/cũ',
          purpose: 'Hiện tên tỉnh/xã lên bản đồ để định vị (bản đồ mới sau sáp nhập hoặc bản đồ cũ).',
          substeps: ['Bấm nút Chuyển layer.', 'Trong nhóm Nhãn hành chính, chọn Nhãn mới (34 tỉnh + xã), Nhãn cũ (63 tỉnh trước đây) hoặc Tắt nhãn.'],
          expected: 'Tên tỉnh/xã hiện khi phóng to đủ mức (xã hiện từ mức zoom xã/phường).',
          image: '/help/user/a07-nhan-hanh-chinh.jpg', route: '/map', tags: ['nhãn', 'hành chính'], related: ['G08'],
        },
        {
          id: 'G10', title: 'Bật/tắt 3D',
          purpose: 'Xem nhà 3D và địa hình nổi cho trực quan (khi dùng nền vector).',
          audience: 'Nút chỉ hiện khi bản đồ đang ở chế độ hỗ trợ 3D.',
          substeps: ['Bấm nút 3D (ô khoanh trong ảnh).', 'Nghiêng/kéo để xoay góc nhìn; bấm lại để về 2D.'],
          expected: 'Nhà nổi khối, địa hình có độ cao khi zoom gần.',
          errors: ['Không thấy nút 3D: bạn đang ở nền raster (vệ tinh/địa hình) — chuyển về Đường phố.'],
          image: '/help/user/a08-3d.jpg', route: '/map', tags: ['3d'], related: ['G08'],
        },
        {
          id: 'G11', title: 'Xem bản đồ lân cận',
          purpose: 'Kiểm tra xung quanh một vị trí có trạm/đề xuất nào chưa, tránh đề xuất trùng.',
          substeps: ['Mở chi tiết một bản ghi (trạm hoặc đề xuất).', 'Bấm nút Xem bản đồ.', 'Chọn bán kính 5 / 10 / 20 / 50 km để xem các điểm xung quanh.'],
          expected: 'Thấy vòng tròn bán kính và các điểm lân cận; dùng để cân nhắc trước khi tạo đề xuất mới.',
          image: '/help/user/g11_ban-do-lan-can.jpg', route: '/map', tags: ['lân cận', 'bán kính'], related: ['G06'],
        },
      ],
    },
    {
      id: 'de-xuat-cua-toi',
      title: 'Đề xuất của tôi',
      icon: 'ClipboardList',
      steps: [
        {
          id: 'G12', title: 'Danh sách đề xuất',
          purpose: 'Theo dõi tất cả đề xuất bạn đã gửi và trạng thái từng cái.',
          substeps: ['Mở trang Đề xuất của tôi.', 'Dùng ô tìm kiếm và bộ lọc trạng thái để tìm nhanh.', 'Bấm vào một dòng để mở chi tiết.'],
          expected: 'Thấy danh sách kèm trạng thái màu (cam chờ duyệt, xanh đang xem xét, xanh lá đã duyệt, đỏ bị từ chối).',
          image: '/help/user/a12-de-xuat-cua-toi.jpg', route: '/my-proposals', tags: ['danh sách', 'đề xuất'], related: ['S04', 'G13'],
        },
        {
          id: 'G12B', title: 'Kiểm tra trùng lặp',
          purpose: 'Phát hiện các đề xuất/trạm nằm quá gần nhau trước khi gửi mới hoặc trước khi duyệt.',
          audience: 'Người dùng ở trang Đề xuất của tôi; ADMIN cũng có panel tương tự ở trang quản trị.',
          substeps: ['Ngay dưới ô tìm kiếm, nhập khoảng cách X (mét, từ trên 200 đến 5000).', 'Bấm nút Check trùng (màu vàng).', 'Xem danh sách các cặp/nhóm điểm gần nhau trong khoảng 200m–X; bấm xem để mở chi tiết hoặc xem trên bản đồ.'],
          expected: 'Biết vị trí nào đã có điểm gần đó để tránh gửi trùng; ADMIN dùng kết quả này khi xét duyệt.',
          errors: ['X phải lớn hơn 200 và tối đa 5000 — nhập ngoài khoảng sẽ báo lỗi.', 'Không ra kết quả: thử tăng X lên.'],
          image: '/help/user/g12b_check-trung.jpg', route: '/my-proposals', tags: ['trùng', 'check', 'khoảng cách'], related: ['G12'],
        },
        {
          id: 'G13', title: 'Xem chi tiết',
          purpose: 'Xem đầy đủ thông tin, file đính kèm và lịch sử một đề xuất.',
          substeps: ['Trong danh sách, bấm vào đề xuất cần xem (đường dẫn dạng /my-proposals/view=id).', 'Kéo xem các trường, file và bản đồ mini.'],
          expected: 'Thấy toàn bộ nội dung đã gửi, biết đang ở trạng thái nào.',
          route: '/my-proposals', tags: ['chi tiết', 'xem'], related: ['G12', 'G14'],
        },
        {
          id: 'G14', title: 'Sửa & Gửi lại',
          purpose: 'Sửa đề xuất khi còn được sửa; gửi lại khi bị từ chối.',
          audience: 'Chỉ sửa được khi đề xuất đang chờ duyệt hoặc bị từ chối.',
          substeps: ['Mở chi tiết, bấm Sửa.', 'Sửa nội dung rồi Lưu.', 'Nếu đề xuất đang bị từ chối, nút lưu hiện chữ Gửi lại — bấm để chuyển về chờ duyệt, người duyệt sẽ nhận thông báo.'],
          expected: 'Đề xuất cập nhật; nếu gửi lại thì trạng thái về chờ duyệt (cam).',
          errors: ['Không thấy nút Sửa: đề xuất đang được xem xét/duyệt thì khóa sửa.'],
          image: '/help/user/a12-de-xuat-cua-toi.jpg', route: '/my-proposals', tags: ['sửa', 'gửi lại'], related: ['S04', 'G16'],
        },
        {
          id: 'G15', title: 'Xóa đề xuất',
          purpose: 'Xóa đề xuất tạo nhầm hoặc không cần nữa.',
          audience: 'Chỉ xóa được đề xuất của chính mình.',
          substeps: ['Trong danh sách, bấm nút Xóa ở dòng cần xóa.', 'Hộp xác nhận hiện ra — đọc kỹ rồi bấm Xóa để chắc chắn, bấm Hủy nếu đổi ý.'],
          expected: 'Đề xuất biến mất khỏi danh sách.',
          errors: ['Đã xóa là mất hẳn, không khôi phục — chắc chắn rồi hãy bấm.'],
          image: '/help/user/g15_xoa-de-xuat.jpg', route: '/my-proposals', tags: ['xóa', 'delete'],
        },
        {
          id: 'G16', title: 'Chuông thông báo',
          purpose: 'Nhận tin khi đề xuất của bạn được duyệt, từ chối hoặc chuyển trạng thái.',
          substeps: ['Bấm biểu tượng chuông ở thanh header.', 'Danh sách hiện các thông báo mới nhất (màu theo trạng thái).', 'Bấm vào một thông báo để nhảy tới đề xuất đó.'],
          expected: 'Không bỏ lỡ kết quả duyệt; số badge trên chuông là tin chưa đọc.',
          image: '/help/user/a14-thong-bao.jpg', route: '/my-proposals', tags: ['thông báo', 'chuông'], related: ['S04'],
        },
      ],
    },
    {
      id: 'khach',
      title: 'Khách (không đăng nhập)',
      icon: 'Send',
      steps: [
        {
          id: 'G17', title: 'Gửi đề xuất không cần tài khoản',
          purpose: 'Người ngoài (chưa có tài khoản) vẫn gửi được đề xuất vị trí.',
          substeps: ['Mở trang Gửi đề xuất (khách).', 'Điền thông tin liên hệ + vị trí trên form.', 'Tích xác thực CAPTCHA rồi bấm Gửi.', 'Ghi lại mã tracking hiện ra để tra cứu sau.'],
          expected: 'Nhận mã tracking; đề xuất vào hàng chờ như người dùng thường.',
          errors: ['Không gửi được do thiếu CAPTCHA: kéo/xác thực xong mới bấm Gửi.', 'Mất mã tracking: không tra cứu được — hãy chụp màn hình khi nhận mã.'],
          image: '/help/user/a13-guest.jpg', route: '/de-xuat', tags: ['guest', 'khách', 'captcha'], related: ['G18'],
        },
        {
          id: 'G18', title: 'Tra cứu & check trùng',
          purpose: 'Dùng mã tracking để xem đề xuất tới đâu; kiểm tra vị trí đã có ai gửi chưa.',
          substeps: ['Mở trang Gửi đề xuất, tìm phần tra cứu.', 'Nhập mã tracking để xem trạng thái (số điện thoại bị che một phần để bảo mật).', 'Trước khi gửi mới, dùng chức năng check trùng để xem gần đó đã có đề xuất/trạm chưa.'],
          expected: 'Biết đề xuất đang chờ duyệt hay đã có kết quả; tránh gửi trùng vị trí.',
          image: '/help/user/g18_tra-cuu-tracking.jpg', route: '/de-xuat', tags: ['tracking', 'tra cứu', 'trùng'], related: ['G17', 'S04'],
        },
      ],
    },
    {
      id: 'dash',
      title: 'Dashboard',
      icon: 'Chart',
      steps: [
        {
          id: 'G19', title: 'Tổng quan',
          purpose: 'Nắm số liệu toàn hệ thống trong một màn hình: người dùng, trạm, đề xuất, tỉ lệ duyệt.',
          audience: 'SUPER_ADMIN, ADMIN, SALES (SALES chỉ số liệu thuộc phạm vi mình).',
          substeps: ['Mở trang Admin (Dashboard).', 'Xem các thẻ số: Users, Stations, Proposals, tỉ lệ duyệt, đề xuất mới 7 ngày.'],
          expected: 'Biết ngay hôm nay có bao nhiêu đề xuất chờ xử lý.',
          image: '/help/admin-data/b01_dashboard.jpg', route: '/admin', tags: ['dashboard'],
        },
      ],
    },
    {
      id: 'users',
      title: 'Quản lý Users',
      icon: 'Users',
      steps: [
        {
          id: 'G20', title: 'Danh sách & cây phân cấp',
          purpose: 'Tìm người dùng, xem ai thuộc nhánh SALES nào (cây SALES → CTV).',
          substeps: ['Mở Quản lý Users.', 'Tìm theo tên/email/SĐT; lọc theo vai trò và trạng thái Hoạt động/Khóa.', 'Mở chế độ cây để xem CTV thuộc SALES nào quản lý.'],
          expected: 'Tìm đúng người trong vài giây, thấy rõ quan hệ quản lý.',
          image: '/help/admin-data/b02_users.jpg', route: '/admin/users', tags: ['users', 'phân cấp'],
        },
        {
          id: 'G21', title: 'Tạo user',
          purpose: 'Thêm tài khoản mới cho nhân sự hoặc cộng tác viên.',
          audience: 'ADMIN, SUPER_ADMIN.',
          prereq: 'Biết vai trò cần gán; CTV cần gắn với một SALES quản lý.',
          substeps: ['Bấm Tạo user.', 'Nhập họ tên, email, SĐT, mật khẩu, chọn vai trò (CTV/SALES/ADMIN) rồi Lưu.'],
          expected: 'Tài khoản mới đăng nhập được ngay.',
          errors: ['Email đã tồn tại: dùng email khác.', 'Chỉ SUPER_ADMIN mới tạo được SUPER_ADMIN.'],
          image: '/help/admin-data/b03_tao-user.jpg', route: '/admin/users', tags: ['tạo user'],
        },
        {
          id: 'G22', title: 'Import / Export users',
          purpose: 'Thêm hàng loạt user từ Excel thay vì tạo từng người; xuất danh sách ra file.',
          substeps: ['Bấm số 1-Template để tải file mẫu, điền đúng cột.', 'Bấm số 3-Import, chọn file → màn Xem trước báo từng dòng lỗi (nếu có) → Xác nhận mới ghi (sai 1 dòng là hủy cả file).', 'Bấm số 2-Export để xuất danh sách hiện tại ra Excel.'],
          expected: 'Hàng chục user được tạo một lúc, dòng nào lỗi thấy rõ trước khi ghi.',
          errors: ['Sai định dạng email/SĐT, trùng email, thiếu cột vai trò — sửa trong file rồi import lại.'],
          image: '/help/admin-data/b04_import-export.jpg', route: '/admin/users', tags: ['import', 'export'],
        },
      ],
    },
    {
      id: 'stations',
      title: 'Quản lý Trạm',
      icon: 'Zap',
      steps: [
        {
          id: 'G23', title: 'Danh sách & lọc',
          purpose: 'Tìm trạm theo trạng thái, loại ưu tiên, mô hình.',
          substeps: ['Mở Quản lý Trạm.', 'Tìm theo tên/địa chỉ; lọc trạng thái (Quy hoạch/Hoạt động/Đang triển khai...), Cấp 1/Cấp 2, mô hình TDT/LK/NQ.'],
          expected: 'Danh sách gọn đúng thứ cần tìm; bấm dòng để xem chi tiết.',
          image: '/help/admin-data/b05_stations.jpg', route: '/admin/stations', tags: ['trạm', 'stations'],
        },
        {
          id: 'G24', title: 'Thêm trạm (tại admin)',
          purpose: 'Tạo trạm mới khi đã chốt vị trí (khác tạo nhanh trên bản đồ ở F3).',
          substeps: ['Bấm Thêm trạm.', 'Nhập form (tọa độ, địa chỉ, mô hình...), hệ thống kiểm tra trùng khoảng cách.', 'Lưu. Loại ưu tiên tự tính từ mô hình (TDT → Cấp 1).'],
          expected: 'Trạm mới hiện trên bản đồ với màu theo trạng thái.',
          errors: ['Báo trùng khoảng cách: mở bản đồ lân cận (G11) kiểm tra rồi hãy lưu.'],
          image: '/help/admin-data/b06-them-tram.jpg', route: '/admin/stations', tags: ['thêm trạm'],
        },
      ],
    },
    {
      id: 'proposals',
      title: 'Quản lý Đề xuất',
      icon: 'ClipboardList',
      steps: [
        {
          id: 'G25', title: 'Danh sách & lọc',
          purpose: 'Tìm đề xuất cần duyệt theo trạng thái và mức ưu tiên.',
          substeps: ['Mở Quản lý Đề xuất.', 'Lọc theo trạng thái (nhãn tiếng Việt: chờ duyệt/đang xem xét/đã duyệt/từ chối) và Cấp 1/Cấp 2.', 'Bấm dòng để Xem/Sửa/Xóa; cột mã 1Office cho biết đã liên kết chưa.'],
          expected: 'Danh sách chờ duyệt gọn gàng, xử lý từng cái nhanh.',
          image: '/help/admin-data/b07_proposals.jpg', route: '/admin/proposals', tags: ['đề xuất', 'proposals'], related: ['G26'],
        },
        {
          id: 'G26', title: 'Duyệt / Đổi trạng thái / Từ chối',
          purpose: 'Xét duyệt đề xuất: cho qua (tự gửi 1Office) hoặc trả về kèm lý do.',
          audience: 'SALES (nhánh mình), ADMIN, SUPER_ADMIN.',
          substeps: [
            'Trong bảng, đổi trạng thái ở cột trạng thái của dòng cần duyệt.',
            'Chọn Duyệt: hiện popup xác nhận (không thể hoàn tác) — bấm Duyệt & gửi 1Office. Hệ thống tự tạo lệnh đẩy sang 1Office, theo dõi trong Audit Log.',
            'Chọn Từ chối: bắt buộc nhập lý do để người gửi biết đường sửa.',
          ],
          expected: 'Chủ đề xuất nhận thông báo; đề xuất được duyệt có lệnh đẩy 1Office (chưa thành trạm thật).',
          errors: ['Duyệt xong không thấy lệnh 1Office: chưa có cấu hình API hoạt động — đẩy thủ công ở F4.'],
          image: '/help/admin-data/b08_trang-thai.jpg', route: '/admin/proposals', tags: ['duyệt', 'từ chối', '1office'], related: ['S04', 'G25'],
        },
      ],
    },
    {
      id: 'fields',
      title: 'Cấu hình trường',
      icon: 'FileText',
      steps: [
        {
          id: 'G27', title: 'Quản lý trường động',
          purpose: 'Định nghĩa các ô nhập liệu dùng trong form (thêm/sửa/xóa trường mà không cần code).',
          audience: 'SUPER_ADMIN.',
          substeps: ['Mở Field Definitions.', 'Bấm Thêm field, chọn kiểu (chữ, số, ngày, chọn 1/nhiều, file, công thức...), chọn lưu cố định hay trong dữ liệu mở rộng.', 'Trường đang dùng có thể Khóa (chống xóa nhầm), Mở khóa hoặc Xóa.'],
          expected: 'Trường mới dùng được ngay trong Form Builder.',
          errors: ['Trường cố định (fixed) không đổi mã, không xóa — đó là cột dữ liệu gốc.'],
          image: '/help/admin-config/c01_fields.jpg', route: '/admin/fields', tags: ['field', 'trường'],
        },
      ],
    },
    {
      id: 'forms',
      title: 'Quản lý Forms',
      icon: 'File',
      steps: [
        {
          id: 'G28', title: 'Danh sách form',
          purpose: 'Mỗi loại phiếu nhập liệu/xem là một form gắn với trạm hoặc đề xuất.',
          substeps: ['Mở Forms Manager.', 'Bấm tạo form mới hoặc Sửa form có sẵn (loại Nhập liệu hoặc Xem/sửa).'],
          expected: 'Form xuất hiện đúng chỗ (lúc tạo mới / lúc xem chi tiết).',
          image: '/help/admin-config/c02_forms.jpg', route: '/admin/forms', tags: ['form'],
        },
        {
          id: 'G29', title: 'Form Builder',
          purpose: 'Xếp trường vào form bằng kéo-thả, chia cột, ẩn/hiện theo điều kiện.',
          substeps: ['Mở form trong Builder.', 'Kéo trường từ danh sách vào từng nhóm (section); chỉnh rộng mấy cột, điều kiện hiện (vd chỉ hiện khi chọn mô hình TDT).', 'Bấm Lưu form.'],
          expected: 'Form ngoài trang nhập liệu đổi theo đúng thiết kế.',
          errors: ['Quên Lưu form: đóng trang là mất công xếp — nhớ bấm Lưu.'],
          image: '/help/admin-config/c03_form-builder.jpg', route: '/admin/forms', tags: ['builder', 'kéo-thả'],
        },
      ],
    },
    {
      id: 'views',
      title: 'Quản lý Views',
      icon: 'LayoutGrid',
      steps: [
        {
          id: 'G30', title: 'Danh sách view',
          purpose: 'Mỗi bảng danh sách (trạm, đề xuất, users) hiện cột nào là do view quyết định.',
          substeps: ['Mở Views Manager.', 'Tạo view mới hoặc Sửa view của từng loại dữ liệu.'],
          expected: 'Bảng ngoài trang hiển thị đúng cột đã cấu hình.',
          image: '/help/admin-config/c04_views.jpg', route: '/admin/views', tags: ['view', 'bảng'],
        },
        {
          id: 'G31', title: 'View Builder',
          purpose: 'Chọn cột, chỉnh rộng, bật/tắt sắp xếp và lọc từng cột.',
          substeps: ['Mở view trong Builder.', 'Kéo-thả để sắp xếp cột; chỉnh độ rộng, bật sắp xếp/lọc, ẩn cột không cần.', 'Bấm Lưu view.'],
          expected: 'Bảng gọn, đúng cột cần, lọc/sắp xếp được.',
          image: '/help/admin-config/c05_view-builder.jpg', route: '/admin/views', tags: ['cột', 'builder'],
        },
      ],
    },
    {
      id: 'data-lists',
      title: 'Data Lists',
      icon: 'List',
      steps: [
        {
          id: 'G32', title: 'Danh mục dùng chung',
          purpose: 'Quản lý các danh mục chọn (tỉnh/xã, mô hình...) dùng chung cho form và địa chỉ.',
          substeps: ['Mở Data Lists, tạo danh mục và định nghĩa các cột.', 'Vào Dữ liệu để thêm từng dòng; dòng con gắn dòng cha để phân cấp (vd xã thuộc tỉnh).', 'Dùng Import/Export khi danh mục dài.'],
          expected: 'Ô chọn trong form và địa chỉ tự điền lấy đúng danh mục này.',
          errors: ['Xóa dòng cha: dòng con mất liên kết (về trống) — kiểm tra lại phân cấp sau khi xóa.'],
          image: '/help/admin-config/c06_data-lists.jpg', route: '/admin/data-lists', tags: ['danh mục', 'data list'],
        },
      ],
    },
    {
      id: 'mapcfg',
      title: 'Bản đồ & Địa chỉ',
      icon: 'Map',
      steps: [
        {
          id: 'G33', title: 'Cấu hình bản đồ',
          purpose: 'Chọn kiểu bản đồ mặc định cả hệ thống dùng (nền, chế độ 2D/3D).',
          substeps: ['Mở Map Config.', 'Chọn kiểu hiển thị, nhà cung cấp nền, chế độ mặc định.', 'Bấm Test kết nối xem nền có tải được không, rồi Lưu cấu hình.'],
          expected: 'Mọi trang bản đồ đổi theo cấu hình mới.',
          errors: ['Nền trắng sau khi đổi: Test báo lỗi thì chọn nguồn khác, đừng lưu cấu hình lỗi.'],
          image: '/help/admin-config/c07_map-config.jpg', route: '/admin/map-config', tags: ['bản đồ', 'map config'],
        },
        {
          id: 'G34', title: 'Cấu hình địa chỉ (Geocode)',
          purpose: 'Bật tự điền địa chỉ từ tọa độ (chọn điểm trên bản đồ là có địa chỉ, tỉnh, xã).',
          substeps: ['Cuối trang Map Config, nhập key Geoapify.', 'Bấm Test rồi Lưu cấu hình địa chỉ.'],
          expected: 'Tạo đề xuất/trạm: chấm tọa độ là địa chỉ tự điền.',
          errors: ['Địa chỉ không tự điền: key sai hoặc hết lượt miễn phí — Test lại key.'],
          image: '/help/admin-config/c08_geocode.jpg', route: '/admin/map-config', tags: ['geocode', 'địa chỉ'],
        },
      ],
    },
    {
      id: 'roles-api',
      title: 'Phân quyền & API',
      icon: 'Shield',
      steps: [
        {
          id: 'G35', title: 'Phân quyền',
          purpose: 'Xem ai được vào trang nào, làm được việc gì (ma trận vai trò).',
          substeps: ['Mở trang Phân quyền.', 'Tra bảng: dòng là trang/chức năng, cột là vai trò.'],
          expected: 'Trả lời được "sao CTV không thấy trang này" trong 1 phút.',
          image: '/help/admin-config/c09_roles.jpg', route: '/admin/roles', tags: ['phân quyền', 'role'], related: ['S02'],
        },
        {
          id: 'G36', title: 'API Configs (1Office)',
          purpose: 'Kết nối hệ thống với 1Office để đẩy đề xuất và đồng bộ nhân sự.',
          substeps: ['Mở API Configs, bấm Thêm API (loại Liên hệ hoặc Nhân sự), nhập địa chỉ + token.', 'Bấm Test để kiểm tra kết nối.', 'Với loại Nhân sự: bấm Đồng bộ để lấy danh sách nhân sự về.'],
          expected: 'Duyệt đề xuất thì tự đẩy được sang 1Office (F4).',
          errors: ['Test báo token sai đối tượng: token Liên hệ và token Nhân sự là 2 token khác nhau.'],
          image: '/help/admin-config/c10_api-configs.jpg', route: '/admin/api-configs', tags: ['api', '1office'],
        },
        {
          id: 'G37', title: 'Field Mapping',
          purpose: 'Ghép từng ô dữ liệu trong app với ô tương ứng bên 1Office để đẩy đúng chỗ.',
          substeps: ['Mở Field Mapping trong API Configs.', 'Kéo/gán trường app ↔ trường 1Office (Desc và File đã ghép sẵn).', 'Lưu.'],
          expected: 'Đề xuất đẩy sang 1Office đầy đủ thông tin, đúng ô.',
          image: '/help/admin-config/c11_mapping.jpg', route: '/admin/api-configs', tags: ['mapping', 'ghép trường'],
        },
        {
          id: 'G38', title: 'Swagger + File bản ghi',
          purpose: 'Tra cứu tài liệu API và xem file đính kèm của từng bản ghi.',
          substeps: ['Mở /api-docs để xem toàn bộ API (cho kỹ thuật).', 'Trong chi tiết bản ghi, mở danh sách file để Xem/Tải. Lệnh đẩy 1Office theo dõi ở Audit Log (F4).'],
          expected: 'Tìm được API cần dùng; tải được file đính kèm.',
          image: '/help/admin-config/c12_swagger.jpg', route: '/admin/api-configs', tags: ['swagger', 'file'],
        },
      ],
    },
  ],
};
