export const groupsGuide = {
  title: 'Nhóm chức năng — học theo từng cụm tính năng',
  sections: [
    {
      id: 'tai-khoan',
      title: 'Tài khoản',
      icon: 'User',
      steps: [
        {
          id: 'G01', title: 'Đăng nhập',
          purpose: 'Vào hệ thống để tạo và theo dõi đề xuất của bạn.',
          audience: 'Tất cả người dùng đã có tài khoản.',
          prereq: 'Có email + mật khẩu do quản trị cấp hoặc tự đăng ký.',
          substeps: ['Mở trang Đăng nhập.', 'Nhập email và mật khẩu rồi bấm nút Đăng nhập (ô khoanh số 1 trong ảnh).'],
          expected: 'Vào trang Bản đồ; tên bạn hiện ở góc màn hình.',
          errors: ['Sai email/mật khẩu: kiểm tra lại, chú ý Caps Lock.', 'Tài khoản bị khóa: liên hệ quản trị.'],
          image: '/help/user/a01_dang-nhap.jpg', route: '/login', tags: ['đăng nhập', 'login'], related: ['G02', 'G05'],
        },
        {
          id: 'G02', title: 'Đăng ký',
          purpose: 'Tạo tài khoản mới khi bạn chưa có.',
          audience: 'Người mới, chưa có tài khoản.',
          substeps: ['Mở trang Đăng ký.', 'Điền họ tên, email, số điện thoại, mật khẩu rồi bấm Đăng ký.'],
          expected: 'Đăng nhập được ngay với tài khoản vừa tạo (vai trò mặc định CTV).',
          errors: ['Email đã tồn tại: dùng email khác hoặc Đăng nhập.', 'Mật khẩu quá ngắn: đặt dài hơn theo gợi ý trên form.'],
          image: '/help/user/a02_dang-ky.jpg', route: '/register', tags: ['đăng ký', 'register'], related: ['G01'],
        },
        {
          id: 'G03', title: 'Đăng xuất',
          purpose: 'Thoát tài khoản khi dùng chung máy hoặc xong việc.',
          substeps: ['Trên máy tính: bấm nút Đăng xuất ở thanh header phía trên.', 'Trên điện thoại: mở menu (3 gạch) rồi bấm Đăng xuất ở cuối.'],
          expected: 'Về trang Đăng nhập; người khác mở máy không vào được tài khoản bạn.',
          image: '/help/user/g03_dang-xuat.jpg', route: '/map', tags: ['đăng xuất', 'logout'],
        },
        {
          id: 'G04', title: 'Hồ sơ cá nhân',
          purpose: 'Xem và cập nhật thông tin của bạn (tên, SĐT...).',
          substeps: ['Vào trang Hồ sơ từ menu.', 'Sửa thông tin rồi bấm Lưu.'],
          expected: 'Thông tin mới hiện ngay trên trang và góc màn hình.',
          image: '/help/user/a03_ho-so.jpg', route: '/profile', tags: ['hồ sơ', 'profile'], related: ['G05'],
        },
        {
          id: 'G05', title: 'Đổi mật khẩu',
          purpose: 'Đổi mật khẩu định kỳ hoặc khi nghi lộ.',
          audience: 'Tất cả người dùng.',
          prereq: 'Đang đăng nhập; nhớ mật khẩu cũ.',
          substeps: ['Vào Hồ sơ, tìm phần đổi mật khẩu.', 'Nhập mật khẩu cũ + mật khẩu mới 2 lần rồi lưu.'],
          expected: 'Đổi xong vẫn ở trong hệ thống; các phiên đăng nhập cũ trên máy khác bị đăng xuất.',
          errors: ['Nhập sai mật khẩu cũ: thử lại cẩn thận.', 'Quên mật khẩu cũ: liên hệ quản trị để đặt lại.'],
          image: '/help/user/g05_doi-mat-khau.jpg', route: '/profile', tags: ['mật khẩu', 'password'], related: ['G04'],
        },
      ],
    },
    {
      id: 'ban-do',
      title: 'Bản đồ & xem dữ liệu',
      icon: 'Map',
      steps: [
        {
          id: 'G06', title: 'Xem marker & chú thích',
          purpose: 'Nhìn tổng thể trạm và đề xuất trên bản đồ, đoán màu là biết tình trạng.',
          substeps: ['Mở trang Bản đồ.', 'Mỗi chấm (marker) là một trạm hoặc đề xuất; bấm vào chấm để xem tóm tắt.', 'Mở bảng Chú thích để tra màu (xem thêm S03).'],
          expected: 'Bạn đọc được bản đồ: đâu là trạm hoạt động, đâu là đề xuất chờ duyệt.',
          errors: ['Bản đồ trắng kèm cảnh báo tile: mạng yếu hoặc nguồn bản đồ lỗi — thử đổi nền khác (G08).'],
          image: '/help/user/a04-ban-do.jpg', route: '/map', tags: ['marker', 'bản đồ'], related: ['S03', 'G07'],
        },
        {
          id: 'G07', title: 'Bộ lọc bản đồ',
          purpose: 'Bớt chấm trên bản đồ để chỉ xem cái mình cần (vd chỉ đề xuất của tôi, chỉ Cấp 1).',
          substeps: ['Bấm nút Bộ lọc bản đồ (ô khoanh số 1 trong ảnh).', 'Chọn phạm vi Của tôi hoặc Tất cả.', 'Tích/bỏ tích Trạm, Đề xuất; chọn trạng thái và Cấp 1/Cấp 2 cần xem.'],
          expected: 'Bản đồ chỉ còn marker đúng điều kiện; đổi lọc là cập nhật ngay.',
          image: '/help/user/a05-bo-loc.jpg', route: '/map', tags: ['bộ lọc', 'filter'], related: ['G06'],
        },
        {
          id: 'G08', title: 'Chuyển nền bản đồ',
          purpose: 'Đổi kiểu nền cho dễ nhìn (đường phố để xem tên đường, vệ tinh để xem địa hình thật).',
          substeps: ['Bấm nút Chuyển layer.', 'Chọn 1 trong 4: Đường phố / Vệ tinh / Vệ tinh + nhãn / Địa hình.'],
          expected: 'Nền đổi ngay, vị trí marker giữ nguyên.',
          image: '/help/user/a06-chuyen-layer.jpg', route: '/map', tags: ['layer', 'vệ tinh'], related: ['G09', 'G10'],
        },
        {
          id: 'G09', title: 'Nhãn hành chính mới/cũ',
          purpose: 'Hiện tên tỉnh/xã lên bản đồ để định vị (bản đồ mới sau sáp nhập hoặc bản đồ cũ).',
          substeps: ['Bấm nút Chuyển layer.', 'Trong nhóm Nhãn hành chính, chọn Nhãn mới (34 tỉnh + xã), Nhãn cũ (63 tỉnh trước đây) hoặc Tắt nhãn.'],
          expected: 'Tên tỉnh/xã hiện khi phóng to đủ mức (xã hiện từ mức zoom xã/phường).',
          image: '/help/user/a07-nhan-hanh-chinh.jpg', route: '/map', tags: ['nhãn', 'hành chính'], related: ['G08'],
        },
        {
          id: 'G10', title: 'Bật/tắt 3D',
          purpose: 'Xem nhà 3D và địa hình nổi cho trực quan (khi dùng nền vector).',
          audience: 'Nút chỉ hiện khi bản đồ đang ở chế độ hỗ trợ 3D.',
          substeps: ['Bấm nút 3D (ô khoanh trong ảnh).', 'Nghiêng/kéo để xoay góc nhìn; bấm lại để về 2D.'],
          expected: 'Nhà nổi khối, địa hình có độ cao khi zoom gần.',
          errors: ['Không thấy nút 3D: bạn đang ở nền raster (vệ tinh/địa hình) — chuyển về Đường phố.'],
          image: '/help/user/a08-3d.jpg', route: '/map', tags: ['3d'], related: ['G08'],
        },
        {
          id: 'G11', title: 'Xem bản đồ lân cận',
          purpose: 'Kiểm tra xung quanh một vị trí có trạm/đề xuất nào chưa, tránh đề xuất trùng.',
          substeps: ['Mở chi tiết một bản ghi (trạm hoặc đề xuất).', 'Bấm nút Xem bản đồ.', 'Chọn bán kính 5 / 10 / 20 / 50 km để xem các điểm xung quanh.'],
          expected: 'Thấy vòng tròn bán kính và các điểm lân cận; dùng để cân nhắc trước khi tạo đề xuất mới.',
          image: '/help/user/g11_ban-do-lan-can.jpg', route: '/map', tags: ['lân cận', 'bán kính'], related: ['G06'],
        },
      ],
    },
    {
      id: 'de-xuat-cua-toi',
      title: 'Đề xuất của tôi',
      icon: 'ClipboardList',
      steps: [
        {
          id: 'G12', title: 'Danh sách đề xuất',
          purpose: 'Theo dõi tất cả đề xuất bạn đã gửi và trạng thái từng cái.',
          substeps: ['Mở trang Đề xuất của tôi.', 'Dùng ô tìm kiếm và bộ lọc trạng thái để tìm nhanh.', 'Bấm vào một dòng để mở chi tiết.', 'Cần gửi vội: bấm nút "Tạo nhanh" — form gọn chỉ có tọa độ + thông tin cơ bản, bổ sung sau cũng được.'],
          expected: 'Thấy danh sách kèm trạng thái màu (cam chờ duyệt, xanh đang xem xét, xanh lá đã duyệt, đỏ bị từ chối).',
          image: '/help/user/a12-de-xuat-cua-toi.jpg', route: '/my-proposals', tags: ['danh sách', 'đề xuất'], related: ['S04', 'G13'],
        },
        {
          id: 'G12B', title: 'Kiểm tra trùng lặp',
          purpose: 'Phát hiện các đề xuất/trạm nằm quá gần nhau trước khi gửi mới hoặc trước khi duyệt.',
          audience: 'Người dùng ở trang Đề xuất của tôi; ADMIN cũng có panel tương tự ở trang quản trị.',
          substeps: ['Ngay dưới ô tìm kiếm, nhập khoảng cách X (mét, từ 0 đến 5000).', 'Bấm nút Check trùng (màu vàng).', 'Xem danh sách các cặp/nhóm điểm gần nhau trong khoảng đã nhập; bấm xem để mở chi tiết hoặc xem trên bản đồ.', 'Bấm "Export trùng" để tải toàn bộ danh sách cặp trùng ra Excel.'],
          expected: 'Biết vị trí nào đã có điểm gần đó để tránh gửi trùng; ADMIN dùng kết quả này khi xét duyệt.',
          errors: ['X tối đa 5000 — nhập ngoài khoảng sẽ báo lỗi.', 'Không ra kết quả: thử tăng X lên.'],
          image: '/help/user/g12b_check-trung.jpg', route: '/my-proposals', tags: ['trùng', 'check', 'khoảng cách'], related: ['G12'],
        },
        {
          id: 'G13', title: 'Xem chi tiết',
          purpose: 'Xem đầy đủ thông tin, file đính kèm và lịch sử một đề xuất.',
          substeps: [
            'Trong danh sách, bấm vào đề xuất cần xem (đường dẫn dạng /my-proposals/view=id).',
            'Kéo xem các trường, file và bản đồ mini.',
            'Bấm vào một file để xem ngay trong trình duyệt: ảnh (kéo phóng to được), video/audio (có nút chơi), PDF, Word/Excel hiển thị tại chỗ; cần lưu về thì bấm Tải.',
          ],
          expected: 'Thấy toàn bộ nội dung đã gửi, biết đang ở trạng thái nào, mở được file không cần tải.',
          errors: ['Không mở/xem được file: file vượt 10MB hoặc định dạng không được hỗ trợ — kiểm tra lại nguồn file.'],
          image: '/help/user/g13_xem-chitiet.jpg', route: '/my-proposals', tags: ['chi tiết', 'xem', 'file', 'đính kèm'], related: ['G12', 'G14', 'G11'],
        },
        {
          id: 'G14', title: 'Sửa & Gửi lại',
          purpose: 'Sửa đề xuất khi còn được sửa; gửi lại khi bị từ chối.',
          audience: 'Chỉ sửa được khi đề xuất đang chờ duyệt hoặc bị từ chối.',
          substeps: ['Mở chi tiết, bấm Sửa.', 'Sửa nội dung rồi Lưu.', 'Nếu đề xuất đang bị từ chối, nút lưu hiện chữ Gửi lại — bấm để chuyển về chờ duyệt, người duyệt sẽ nhận thông báo.'],
          expected: 'Đề xuất cập nhật; nếu gửi lại thì trạng thái về chờ duyệt (cam).',
          errors: ['Không thấy nút Sửa: đề xuất đang được xem xét/duyệt thì khóa sửa.'],
          image: '/help/user/a12-de-xuat-cua-toi.jpg', route: '/my-proposals', tags: ['sửa', 'gửi lại'], related: ['S04', 'G16'],
        },
        {
          id: 'G39', title: 'Đề xuất mô hình NQ_LK (tab lồng)',
          purpose: 'Điền đúng thông tin khi chọn mô hình đầu tư "Nhượng quyền + Liên kết" — form sẽ tự hiện thêm cụm tab lồng.',
          audience: 'Người tạo đề xuất theo mô hình hỗn hợp vừa nhượng quyền vừa liên kết.',
          substeps: [
            'Trong form đề xuất, ở mục Mô hình đầu tư, chọn "Nhượng quyền + Liên kết" (NQ_LK).',
            'Form xuất hiện cụm tab "Nhượng quyền và Liên kết" gồm 2 tab con: "Nhượng quyền" và "Liên kết" — kiểm tra đủ cả hai tab trước khi gửi.',
            'Tab Nhượng quyền: điền Chính sách, Loại trừ và các trường nhượng quyền khác.',
            'Tab Liên kết: điền Chính sách, Loại trừ, Đặt cọc (+ ghi chú); phần "Chi phí" là bảng nhiều dòng — bấm thêm dòng, chọn Loại chi phí thì Số tiền tự điền theo đơn giá (có thể sửa), mỗi dòng phải đủ cả hai cột.',
            'Tổng chi phí là trường công thức, tự cộng từ bảng chi phí và loại trừ — không điền tay.',
          ],
          expected: 'Gửi xong, mã đề xuất có dạng NQ_LK_...; đầy đủ cả số liệu nhượng quyền lẫn liên kết.',
          errors: [
            'Không thấy 2 tab: kiểm tra lại đã chọn đúng mô hình "Nhượng quyền + Liên kết" chưa.',
            'Báo "Chi phí: dòng N thiếu ...": mỗi dòng bảng chi phí phải điền đủ cả Loại chi phí và Số tiền.',
          ],
          image: '/help/user/g39_nqlk.jpg', route: '/my-proposals', tags: ['nq_lk', 'nhượng quyền', 'liên kết', 'chi phí', 'tab'], related: ['S03', 'G14'],
        },
        {
          id: 'G15', title: 'Xóa đề xuất',
          purpose: 'Xóa đề xuất tạo nhầm hoặc không cần nữa.',
          audience: 'Chỉ xóa được đề xuất của chính mình.',
          substeps: ['Trong danh sách, bấm nút Xóa ở dòng cần xóa.', 'Hộp xác nhận hiện ra — đọc kỹ rồi bấm Xóa để chắc chắn, bấm Hủy nếu đổi ý.'],
          expected: 'Đề xuất biến mất khỏi danh sách.',
          errors: ['Đã xóa là mất hẳn, không khôi phục — chắc chắn rồi hãy bấm.'],
          image: '/help/user/g15_xoa-de-xuat.jpg', route: '/my-proposals', tags: ['xóa', 'delete'],
        },
        {
          id: 'G16', title: 'Chuông thông báo',
          purpose: 'Nhận tin khi đề xuất của bạn được duyệt, từ chối hoặc chuyển trạng thái.',
          audience: 'Mọi tài khoản; ADMIN/SUPER_ADMIN có thêm tab "Tất cả" để xem thông báo của mọi người (chỉ đọc).',
          substeps: [
            'Bấm biểu tượng chuông ở thanh header.',
            'Danh sách hiện các thông báo mới nhất (màu theo trạng thái: đỏ từ chối, xanh lá duyệt, vàng chờ, xanh dương đang xem xét, vàng nghệ gửi lại).',
            'Bấm vào một thông báo để nhảy tới đề xuất đó.',
            'Lưu ý: danh sách chỉ tính thông báo trong 7 ngày gần nhất — tin cũ hơn tự ẩn khỏi chuông.',
          ],
          expected: 'Không bỏ lỡ kết quả duyệt; số badge trên chuông là tin chưa đọc.',
          image: '/help/user/a14-thong-bao.jpg', route: '/my-proposals', tags: ['thông báo', 'chuông'], related: ['S04'],
        },
      ],
    },
    {
      id: 'khach',
      title: 'Khách (không đăng nhập)',
      icon: 'Send',
      steps: [
        {
          id: 'G17', title: 'Gửi đề xuất không cần tài khoản',
          purpose: 'Người ngoài (chưa có tài khoản) vẫn gửi được đề xuất vị trí.',
          substeps: ['Mở trang Gửi đề xuất (khách).', 'Điền thông tin liên hệ + vị trí trên form.', 'Tích xác thực CAPTCHA rồi bấm Gửi.', 'Ghi lại mã tracking hiện ra để tra cứu sau.'],
          expected: 'Nhận mã tracking; đề xuất vào hàng chờ như người dùng thường.',
          errors: ['Không gửi được do thiếu CAPTCHA: kéo/xác thực xong mới bấm Gửi.', 'Mất mã tracking: không tra cứu được — hãy chụp màn hình khi nhận mã.'],
          image: '/help/user/a13-guest.jpg', route: '/de-xuat', tags: ['guest', 'khách', 'captcha'], related: ['G18'],
        },
        {
          id: 'G18', title: 'Tra cứu & check trùng',
          purpose: 'Dùng mã tracking để xem đề xuất tới đâu; kiểm tra vị trí đã có ai gửi chưa.',
          substeps: ['Mở trang Gửi đề xuất, tìm phần tra cứu.', 'Nhập mã tracking để xem trạng thái (số điện thoại bị che một phần để bảo mật).', 'Trước khi gửi mới, dùng chức năng check trùng để xem gần đó đã có đề xuất/trạm chưa.'],
          expected: 'Biết đề xuất đang chờ duyệt hay đã có kết quả; tránh gửi trùng vị trí.',
          image: '/help/user/g18_tra-cuu-tracking.jpg', route: '/de-xuat', tags: ['tracking', 'tra cứu', 'trùng'], related: ['G17', 'S04'],
        },
      ],
    },
    {
      id: 'dash',
      title: 'Dashboard',
      icon: 'Chart',
      steps: [
        {
          id: 'G19', title: 'Tổng quan',
          purpose: 'Nắm số liệu toàn hệ thống trong một màn hình: người dùng, trạm, đề xuất, tỉ lệ duyệt.',
          audience: 'SUPER_ADMIN, ADMIN, SALES (SALES chỉ số liệu thuộc phạm vi mình).',
          substeps: ['Mở trang Admin (Dashboard).', 'Xem các thẻ số: Users, Stations, Proposals, tỉ lệ duyệt, đề xuất mới 7 ngày.'],
          expected: 'Biết ngay hôm nay có bao nhiêu đề xuất chờ xử lý.',
          image: '/help/admin-data/b01_dashboard.jpg', route: '/admin', tags: ['dashboard'],
        },
        {
          id: 'G41', title: 'Audit Log (nhật ký đồng bộ)',
          purpose: 'Theo dõi mọi lệnh đẩy/lấy dữ liệu với 1Office và xử lý lệnh kẹt/lỗi.',
          audience: 'ADMIN, SUPER_ADMIN; SALES chỉ thấy log của chính mình.',
          substeps: [
            'Mở Audit Log từ menu quản trị.',
            'Lọc theo trạng thái, hướng (Push → 1Office / Pull ← 1Office) hoặc Action; bấm Lọc / Xóa bộ lọc / Làm mới.',
            'Bấm biểu tượng mắt ở dòng lệnh để xem chi tiết nội dung đã gửi và kết quả trả về.',
            'Lệnh lỗi hoặc treo: chỉ SUPER_ADMIN thấy nút Retry (chạy lại) và Cancel (bỏ lệnh).',
          ],
          expected: 'Biết đề xuất nào đã đẩy thành công, lệnh nào đang chờ hay lỗi và vì sao.',
          errors: ['Không thấy nút Retry/Cancel: hai nút này chỉ hiện cho SUPER_ADMIN.'],
          image: '/help/admin-data/b10_audit.jpg', route: '/admin/audit-log', tags: ['audit', 'log', 'retry', 'queue'], related: ['G36', 'G38'],
        },
      ],
    },
    {
      id: 'users',
      title: 'Quản lý Users',
      icon: 'Users',
      steps: [
        {
          id: 'G20', title: 'Danh sách & cây phân cấp',
          purpose: 'Tìm người dùng, xem ai thuộc nhánh SALES nào (cây SALES → CTV).',
          substeps: ['Mở Quản lý Users.', 'Tìm theo tên/email/SĐT; lọc theo vai trò và trạng thái Hoạt động/Khóa.', 'Mở chế độ cây để xem CTV thuộc SALES nào quản lý.'],
          expected: 'Tìm đúng người trong vài giây, thấy rõ quan hệ quản lý.',
          image: '/help/admin-data/b02_users.jpg', route: '/admin/users', tags: ['users', 'phân cấp'],
        },
        {
          id: 'G21', title: 'Tạo user',
          purpose: 'Thêm tài khoản mới cho nhân sự hoặc cộng tác viên.',
          audience: 'ADMIN, SUPER_ADMIN.',
          prereq: 'Biết vai trò cần gán; CTV cần gắn với một SALES quản lý.',
          substeps: [
            'Bấm Tạo user.',
            'Nhập họ tên, email, SĐT, mật khẩu, chọn vai trò (CTV/NPP/SALES/ADMIN) rồi Lưu.',
            'Người dùng nghỉ tạm: bấm Khóa ở dòng của họ (không đăng nhập được nữa); bấm Mở để cho vào lại.',
            'Họ quên mật khẩu: bấm Đổi MK, nhập mật khẩu mới (tối thiểu 6 ký tự) — mọi phiên đăng nhập cũ của người đó sẽ bị thoát.',
          ],
          expected: 'Tài khoản mới đăng nhập được ngay; khóa/mở và đặt lại mật khẩu làm trực tiếp trên danh sách.',
          errors: ['Email đã tồn tại: dùng email khác.', 'Chỉ SUPER_ADMIN mới tạo/sửa được SUPER_ADMIN; nút Khóa không hiện với SALES.'],
          image: '/help/admin-data/b03_tao-user.jpg', route: '/admin/users', tags: ['tạo user'],
        },
        {
          id: 'G22', title: 'Import / Export users',
          purpose: 'Thêm hàng loạt user từ Excel thay vì tạo từng người; xuất danh sách ra file.',
          substeps: ['Bấm số 1-Template để tải file mẫu, điền đúng cột.', 'Bấm số 3-Import, chọn file → màn Xem trước báo từng dòng lỗi (nếu có) → Xác nhận mới ghi (sai 1 dòng là hủy cả file).', 'Bấm số 2-Export để xuất danh sách hiện tại ra Excel.'],
          expected: 'Hàng chục user được tạo một lúc, dòng nào lỗi thấy rõ trước khi ghi.',
          errors: ['Sai định dạng email/SĐT, trùng email, thiếu cột vai trò — sửa trong file rồi import lại.'],
          image: '/help/admin-data/b04_import-export.jpg', route: '/admin/users', tags: ['import', 'export'],
        },
        {
          id: 'G42', title: 'Gán mã nhân sự 1Office cho user',
          purpose: 'Liên kết tài khoản trong app với người thật bên 1Office, để khi đẩy đề xuất các ô "Người phụ trách" khớp đúng người.',
          audience: 'ADMIN, SUPER_ADMIN.',
          prereq: 'Danh sách nhân sự 1Office đã được đồng bộ (Cấu hình API → cấu hình loại Nhân sự → Đồng bộ — xem G36).',
          substeps: [
            'Mở Xem chi tiết một người dùng ở trang Quản lý Users.',
            'Kéo xuống mục "Liên kết hệ thống": giữ nguyên hệ thống "1office", chọn nhân sự theo "Mã NS - Tên" rồi bấm Lưu.',
            'Người bị xám trong danh sách (kèm chữ "chưa có tài khoản 1Office") là người chưa có tài khoản bên đó — không gán và không giao việc được.',
            'Đổi liên kết: bấm Xóa ở dòng liên kết cũ rồi gán người mới.',
          ],
          expected: 'User này chọn được trong ô nhân sự của đề xuất và đẩy sang 1Office đúng người.',
          errors: [
            'Danh sách nhân sự trống: vào Cấu hình API → loại "1office nhân sự" → bấm Đồng bộ trước.',
            'Vẫn báo lỗi người phụ trách khi đẩy: người đó có thể đổi mã bên 1Office — đồng bộ nhân sự rồi gán lại.',
          ],
          image: '/help/admin-data/g42_gan-ma-ns.jpg', route: '/admin/users', tags: ['nhân sự', '1office', 'liên kết', 'external'], related: ['G36', 'G26'],
        },
      ],
    },
    {
      id: 'stations',
      title: 'Quản lý Trạm',
      icon: 'Zap',
      steps: [
        {
          id: 'G23', title: 'Danh sách & lọc',
          purpose: 'Tìm trạm theo trạng thái, loại ưu tiên, mô hình.',
          substeps: ['Mở Quản lý Trạm.', 'Tìm theo tên/địa chỉ; lọc trạng thái (Quy hoạch/Hoạt động/Đang triển khai...), Cấp 1/Cấp 2, mô hình TDT/LK/NQ.'],
          expected: 'Danh sách gọn đúng thứ cần tìm; bấm dòng để xem chi tiết.',
          image: '/help/admin-data/b05_stations.jpg', route: '/admin/stations', tags: ['trạm', 'stations'],
        },
        {
          id: 'G24', title: 'Thêm trạm (tại admin)',
          purpose: 'Tạo trạm mới khi đã chốt vị trí (khác tạo nhanh trên bản đồ ở F3).',
          substeps: ['Bấm Thêm trạm.', 'Nhập form (tọa độ, địa chỉ, mô hình...), hệ thống kiểm tra trùng khoảng cách.', 'Lưu. Loại ưu tiên tự tính từ mô hình (TDT → Cấp 1).'],
          expected: 'Trạm mới hiện trên bản đồ với màu theo trạng thái.',
          errors: ['Báo trùng khoảng cách: mở bản đồ lân cận (G11) kiểm tra rồi hãy lưu.'],
          image: '/help/admin-data/b06-them-tram.jpg', route: '/admin/stations', tags: ['thêm trạm'],
        },
      ],
    },
    {
      id: 'proposals',
      title: 'Quản lý Đề xuất',
      icon: 'ClipboardList',
      steps: [
        {
          id: 'G25', title: 'Danh sách & lọc',
          purpose: 'Tìm đề xuất cần duyệt theo trạng thái và mức ưu tiên.',
          substeps: ['Mở Quản lý Đề xuất.', 'Lọc theo trạng thái (nhãn tiếng Việt: chờ duyệt/đang xem xét/đã duyệt/từ chối) và Cấp 1/Cấp 2.', 'Bấm dòng để Xem/Sửa/Xóa; cột mã 1Office cho biết đã liên kết chưa.'],
          expected: 'Danh sách chờ duyệt gọn gàng, xử lý từng cái nhanh.',
          image: '/help/admin-data/b07_proposals.jpg', route: '/admin/proposals', tags: ['đề xuất', 'proposals'], related: ['G26'],
        },
        {
          id: 'G26', title: 'Duyệt / Đổi trạng thái / Từ chối',
          purpose: 'Xét duyệt đề xuất: cho qua (tự gửi 1Office) hoặc trả về kèm lý do.',
          audience: 'SALES (nhánh mình), ADMIN, SUPER_ADMIN.',
          substeps: [
            'Trong bảng, đổi trạng thái ở cột trạng thái của dòng cần duyệt.',
            'Chọn Duyệt: hiện popup xác nhận (không thể hoàn tác) — bấm Duyệt & gửi 1Office. Hệ thống tự tạo lệnh đẩy sang 1Office, theo dõi trong Audit Log.',
            'Chọn Từ chối: bắt buộc nhập lý do để người gửi biết đường sửa.',
          ],
          expected: 'Chủ đề xuất nhận thông báo; đề xuất được duyệt có lệnh đẩy 1Office (chưa thành trạm thật).',
          errors: [
            'Duyệt bị chặn kèm cảnh báo thiếu "Người đang phụ trách" / "Người giao phụ trách": mở Sửa đề xuất, chọn đủ 2 ô nhân sự rồi duyệt lại (nhân sự phải đã gán mã 1Office — xem G42).',
            'Duyệt xong không thấy lệnh 1Office: chưa có cấu hình API hoạt động — đẩy thủ công ở F4.',
          ],
          image: '/help/admin-data/b08_trang-thai.jpg', route: '/admin/proposals', tags: ['duyệt', 'từ chối', '1office'], related: ['S04', 'G25'],
        },
        {
          id: 'G40', title: 'Excel: Template / Export / Import theo bộ cột',
          purpose: 'Nhập – xuất hàng loạt bằng Excel, chọn đúng bộ cột cần dùng thay vì phụ thuộc một mẫu cố định.',
          audience: 'ADMIN, SUPER_ADMIN (SALES không thấy nút Template/Import ở trang Quản lý Đề xuất). Trang Đề xuất của tôi cũng có bản gọn: Export (theo bảng / theo form) + Import cho chính danh sách của bạn.',
          substeps: [
            'Bấm mũi tên cạnh nút Template hoặc Export để chọn bộ cột: Bảng chính / Đầy đủ / Cơ bản, hoặc "Tất cả bộ cột (1 file, nhiều sheet)"; riêng Export còn có "Theo form" — xuất đúng layout form (section/tab, 3 hàng header).',
            'Cần nhập dữ liệu: tải Template đúng bộ cột dự định import rồi điền vào file.',
            'Bấm Import → chọn "Bộ cột" → chọn file: hệ thống tự nhận diện bộ cột khớp với file, cảnh báo vàng các cột bị bỏ qua / thiếu trường để trống; có thể chọn lại bộ cột khác.',
            'Xem trước → từng dòng lỗi được chỉ rõ lý do → Xác nhận: chỉ ghi khi cả file hợp lệ, sai 1 dòng là hủy toàn bộ.',
            'Quản lý Trạm và Quản lý Users có đúng bộ nút Template/Export/Import này.',
          ],
          expected: 'File tải về tự đặt tên kèm ngày giờ; nhập hàng trăm dòng một lần và biết chính xác dòng nào lỗi trước khi ghi.',
          errors: [
            'Bị từ chối ngay ở xem trước: thiếu cột bắt buộc (đề xuất cần vĩ độ/kinh độ; trạm cần tên + vĩ độ + kinh độ; users cần họ tên + email).',
            'Không nhận diện được bộ cột (báo đỏ): bấm chọn tay "Bộ cột" thay vì để tự động.',
            'Giá trị ô chọn (select) không có trong danh mục: sửa lại đúng nhãn hoặc bổ sung Data List (G32).',
          ],
          image: '/help/admin-data/g40_excel-bo-cot.jpg', route: '/admin/proposals', tags: ['excel', 'import', 'export', 'bộ cột', 'template'], related: ['G22', 'G30', 'G31'],
        },
      ],
    },
    {
      id: 'fields',
      title: 'Cấu hình trường',
      icon: 'FileText',
      steps: [
        {
          id: 'G27', title: 'Quản lý trường động',
          purpose: 'Định nghĩa các ô nhập liệu dùng trong form (thêm/sửa/xóa trường mà không cần code).',
          audience: 'SUPER_ADMIN.',
          substeps: [
            'Mở Field Definitions.',
            'Bấm Thêm field, chọn kiểu (chữ, số, ngày, chọn 1/nhiều, file, công thức...), chọn lưu cố định hay trong dữ liệu mở rộng.',
            'Kiểu "Người dùng" (user): hiển thị ô chọn nhân sự theo "Mã NS - Tên"; cấu hình tự điền (chính tôi / SALES quản lý / chủ hoặc quản lý) và khóa ô nếu người dùng không được sửa.',
            'Kiểu "Công thức" (formula): mở trình soạn thảo trực quan — bấm chọn trường, hàm (IF, SUM, ROUND, SEQ sinh mã tự tăng...), toán tử; có nút kiểm tra hợp lệ và xem trước kết quả. Công thức tính trước khi gửi (trong form) hoặc tính sau khi tạo bản ghi (dùng được cả mã bản ghi, ngày tạo...).',
            'Trường đang dùng có thể Khóa (chống xóa nhầm), Mở khóa hoặc Xóa.',
          ],
          expected: 'Trường mới dùng được ngay trong Form Builder; ô nhân sự và ô tự tính hoạt động đúng cấu hình.',
          errors: ['Trường cố định (fixed) không đổi mã, không xóa — đó là cột dữ liệu gốc.'],
          image: '/help/admin-config/c01_fields.jpg', route: '/admin/fields', tags: ['field', 'trường'],
        },
      ],
    },
    {
      id: 'forms',
      title: 'Quản lý Forms',
      icon: 'File',
      steps: [
        {
          id: 'G28', title: 'Danh sách form',
          purpose: 'Mỗi loại phiếu nhập liệu/xem là một form gắn với trạm hoặc đề xuất.',
          substeps: [
            'Mở Forms Manager.',
            'Bấm tạo form mới hoặc Sửa form có sẵn (loại Nhập liệu hoặc Xem/sửa).',
            'Một nơi có thể có nhiều bản form: bản badge "Mặc định" được dùng tự động; form hệ thống có badge "Khóa" — không xóa được nhưng vẫn sửa nội dung được.',
            'Form loại "Tạo nhanh" chỉ hiện khi bấm nút Tạo nhanh — gọn hơn form đầy đủ.',
          ],
          expected: 'Form xuất hiện đúng chỗ (lúc tạo mới / lúc xem chi tiết / nút Tạo nhanh).',
          image: '/help/admin-config/c02_forms.jpg', route: '/admin/forms', tags: ['form'],
        },
        {
          id: 'G29', title: 'Form Builder',
          purpose: 'Xếp trường vào form bằng kéo-thả, chia cột, ẩn/hiện theo điều kiện.',
          substeps: ['Mở form trong Builder.', 'Kéo trường từ danh sách vào từng nhóm (section); chỉnh rộng mấy cột, điều kiện hiện (vd chỉ hiện khi chọn mô hình TDT).', 'Bấm Lưu form.'],
          expected: 'Form ngoài trang nhập liệu đổi theo đúng thiết kế.',
          errors: ['Quên Lưu form: đóng trang là mất công xếp — nhớ bấm Lưu.'],
          image: '/help/admin-config/c03_form-builder.jpg', route: '/admin/forms', tags: ['builder', 'kéo-thả'],
        },
      ],
    },
    {
      id: 'views',
      title: 'Quản lý Views',
      icon: 'LayoutGrid',
      steps: [
        {
          id: 'G30', title: 'Danh sách view',
          purpose: 'Mỗi bảng danh sách (trạm, đề xuất, users) hiện cột nào là do view quyết định.',
          substeps: [
            'Mở Views Manager.',
            'Tạo view mới hoặc Sửa view của từng loại dữ liệu.',
            'Mỗi view gắn với một mục đích dùng (badge "Dùng ở đâu"): Bảng chính = bảng danh sách trên màn hình; Đầy đủ / Cơ bản = các bộ cột khi làm Excel (Template/Export/Import).',
            'View hệ thống có badge "Khóa" — không xóa được nhưng vẫn đổi trạng thái và sửa được.',
          ],
          expected: 'Bảng ngoài trang hiển thị đúng cột đã cấu hình.',
          image: '/help/admin-config/c04_views.jpg', route: '/admin/views', tags: ['view', 'bảng'],
        },
        {
          id: 'G31', title: 'View Builder',
          purpose: 'Chọn cột, chỉnh rộng, bật/tắt sắp xếp và lọc từng cột.',
          substeps: ['Mở view trong Builder.', 'Kéo-thả để sắp xếp cột; chỉnh độ rộng, bật sắp xếp/lọc, ẩn cột không cần.', 'Bấm Lưu view.'],
          expected: 'Bảng gọn, đúng cột cần, lọc/sắp xếp được.',
          image: '/help/admin-config/c05_view-builder.jpg', route: '/admin/views', tags: ['cột', 'builder'],
        },
      ],
    },
    {
      id: 'data-lists',
      title: 'Data Lists',
      icon: 'List',
      steps: [
        {
          id: 'G32', title: 'Danh mục dùng chung',
          purpose: 'Quản lý các danh mục chọn (tỉnh/xã, mô hình...) dùng chung cho form và địa chỉ.',
          substeps: [
            'Mở Data Lists, tạo danh mục và định nghĩa các cột.',
            'Vào Dữ liệu để thêm từng dòng; dòng con gắn dòng cha để phân cấp (vd xã thuộc tỉnh).',
            'Nhờ phân cấp này mà ô "chọn 1" có thể nối Cha → Con: chọn tỉnh trước thì ô xã chỉ hiện các xã thuộc tỉnh đó (cascading).',
            'Dùng Import/Export khi danh mục dài.',
          ],
          expected: 'Ô chọn trong form và địa chỉ tự điền lấy đúng danh mục này.',
          errors: ['Xóa dòng cha: dòng con mất liên kết (về trống) — kiểm tra lại phân cấp sau khi xóa.'],
          image: '/help/admin-config/c06_data-lists.jpg', route: '/admin/data-lists', tags: ['danh mục', 'data list'],
        },
      ],
    },
    {
      id: 'mapcfg',
      title: 'Bản đồ & Địa chỉ',
      icon: 'Map',
      steps: [
        {
          id: 'G33', title: 'Cấu hình bản đồ',
          purpose: 'Chọn kiểu bản đồ mặc định cả hệ thống dùng (nền, chế độ 2D/3D).',
          substeps: ['Mở Map Config.', 'Chọn kiểu hiển thị, nhà cung cấp nền, chế độ mặc định.', 'Bấm Test kết nối xem nền có tải được không, rồi Lưu cấu hình.'],
          expected: 'Mọi trang bản đồ đổi theo cấu hình mới.',
          errors: ['Nền trắng sau khi đổi: Test báo lỗi thì chọn nguồn khác, đừng lưu cấu hình lỗi.'],
          image: '/help/admin-config/c07_map-config.jpg', route: '/admin/map-config', tags: ['bản đồ', 'map config'],
        },
        {
          id: 'G34', title: 'Cấu hình địa chỉ (Geocode)',
          purpose: 'Bật tự điền địa chỉ từ tọa độ (chọn điểm trên bản đồ là có địa chỉ, tỉnh, xã).',
          substeps: ['Cuối trang Map Config, nhập key Geoapify.', 'Bấm Test rồi Lưu cấu hình địa chỉ.'],
          expected: 'Tạo đề xuất/trạm: chấm tọa độ là địa chỉ tự điền.',
          errors: ['Địa chỉ không tự điền: key sai hoặc hết lượt miễn phí — Test lại key.'],
          image: '/help/admin-config/c08_geocode.jpg', route: '/admin/map-config', tags: ['geocode', 'địa chỉ'],
        },
      ],
    },
    {
      id: 'roles-api',
      title: 'Phân quyền & API',
      icon: 'Shield',
      steps: [
        {
          id: 'G35', title: 'Phân quyền',
          purpose: 'Xem ai được vào trang nào, làm được việc gì (ma trận vai trò).',
          substeps: ['Mở trang Phân quyền.', 'Tra bảng: dòng là trang/chức năng, cột là vai trò.'],
          expected: 'Trả lời được "sao CTV không thấy trang này" trong 1 phút.',
          image: '/help/admin-config/c09_roles.jpg', route: '/admin/roles', tags: ['phân quyền', 'role'], related: ['S02'],
        },
        {
          id: 'G36', title: 'API Configs (1Office)',
          purpose: 'Kết nối hệ thống với 1Office để đẩy đề xuất và đồng bộ nhân sự.',
          substeps: ['Mở API Configs, bấm Thêm API (loại Liên hệ hoặc Nhân sự), nhập địa chỉ + token.', 'Bấm Test để kiểm tra kết nối.', 'Với loại Nhân sự: bấm Đồng bộ để lấy danh sách nhân sự về.'],
          expected: 'Duyệt đề xuất thì tự đẩy được sang 1Office (F4).',
          errors: ['Test báo token sai đối tượng: token Liên hệ và token Nhân sự là 2 token khác nhau.'],
          image: '/help/admin-config/c10_api-configs.jpg', route: '/admin/api-configs', tags: ['api', '1office'],
        },
        {
          id: 'G37', title: 'Field Mapping',
          purpose: 'Ghép từng ô dữ liệu trong app với ô tương ứng bên 1Office để đẩy đúng chỗ.',
          substeps: ['Mở Field Mapping trong API Configs.', 'Kéo/gán trường app ↔ trường 1Office (Desc và File đã ghép sẵn).', 'Lưu.'],
          expected: 'Đề xuất đẩy sang 1Office đầy đủ thông tin, đúng ô.',
          image: '/help/admin-config/c11_mapping.jpg', route: '/admin/api-configs', tags: ['mapping', 'ghép trường'],
        },
        {
          id: 'G38', title: 'Swagger + File bản ghi',
          purpose: 'Tra cứu tài liệu API và xem file đính kèm của từng bản ghi.',
          substeps: [
            'Mở /api-docs để xem toàn bộ API (cho kỹ thuật).',
            'Trong chi tiết bản ghi, mở danh sách file để xem ngay trong trình duyệt (ảnh/video/PDF/Word/Excel) hoặc Tải.',
            'Trang "Tệp của bản ghi" trong menu quản trị liệt kê mọi file của một bản ghi: tải từng file hoặc tải tất cả cùng lúc.',
            'Lệnh đẩy 1Office theo dõi ở Audit Log (F4).',
          ],
          expected: 'Tìm được API cần dùng; xem/tải được file đính kèm mà không cần mở từng cái một.',
          errors: ['Tải lên bị chặn: mỗi file tối đa 10MB; định dạng thực thi/HTML/SVG bị từ chối vì bảo mật — đổi sang PDF/ảnh rồi tải lại.'],
          image: '/help/admin-config/c12_swagger.jpg', route: '/admin/api-configs', tags: ['swagger', 'file'],
        },
      ],
    },
    {
      id: 'faq',
      title: 'Câu hỏi thường gặp',
      icon: 'Help',
      steps: [
        {
          id: 'Q01', title: 'Duyệt xong sao đề xuất chưa thành trạm?',
          text: 'Được duyệt nghĩa là hồ sơ đạt và đã có lệnh tự đẩy sang 1Office — chưa phải trạm thật. Trạm thật tạo riêng ở Quản lý Trạm hoặc nút "Tạo trạm nhanh" trên bản đồ (F3).',
          tags: ['trạm', 'duyệt'], related: ['S04', 'G24'],
        },
        {
          id: 'Q02', title: 'Sao tôi không thấy trang Cấu hình?',
          text: 'Các trang Field/Form/View/Data List/Map/Phân quyền/API chỉ SUPER_ADMIN thấy; SALES chỉ có 4 trang quản lý dữ liệu; CTV/NPP chỉ có khu vực người dùng. Đây là phân quyền, không phải lỗi — tra nhanh ở G35.',
          tags: ['phân quyền', 'menu'], related: ['S02', 'G35'],
        },
        {
          id: 'Q03', title: 'Vì sao đề xuất không còn nút Sửa?',
          text: 'Chỉ sửa được khi đề xuất đang Chờ duyệt hoặc Bị từ chối. Đã chuyển sang Đang xem xét hoặc Đã duyệt thì khóa sửa; bị từ chối thì sửa xong bấm "Gửi lại".',
          tags: ['sửa', 'khóa'], related: ['G14'],
        },
        {
          id: 'Q04', title: 'Mất mã tracking thì làm sao?',
          text: 'Mã tracking là cách duy nhất để tra cứu đề xuất của khách (không đăng nhập). Mất mã thì không tự tra được — hãy nhờ người có tài khoản kiểm tra hộ hoặc liên hệ quản trị. Lần sau nên chụp màn hình ngay khi nhận mã.',
          tags: ['tracking', 'khách'], related: ['G17', 'G18'],
        },
        {
          id: 'Q05', title: 'Bản đồ trắng hoặc báo lỗi tile?',
          text: 'Thường do mạng yếu hoặc nguồn nền đang lỗi (kèm banner cảnh báo). Thử đổi nền khác ở "Chuyển layer"; nếu mọi nền đều lỗi, báo quản trị kiểm tra Cấu hình bản đồ (G33).',
          tags: ['trắng', 'tile', 'lỗi'], related: ['G08', 'G33'],
        },
        {
          id: 'Q06', title: 'Tin thông báo cũ đâu mất rồi?',
          text: 'Chuông chỉ hiển thị thông báo trong 7 ngày gần nhất để danh sách gọn. Lịch sử đầy đủ của đề xuất vẫn xem ở chi tiết từng đề xuất.',
          tags: ['thông báo', '7 ngày'], related: ['G16'],
        },
        {
          id: 'Q07', title: 'Tệp đính kèm không tải lên được?',
          text: 'Mỗi file tối đa 10MB; chỉ nhận tài liệu/ảnh/pdf thông dụng — file thực thi, HTML, SVG bị chặn vì bảo mật. Nén, đổi sang PDF, hoặc tách nhỏ rồi tải lại.',
          tags: ['file', '10MB', 'upload'], related: ['G13', 'G38'],
        },
        {
          id: 'Q08', title: 'Bấm Duyệt bị chặn, báo thiếu nhân sự?',
          text: 'Đề xuất còn trống "Người phụ trách" hoặc "Người giao phụ trách" — bắt buộc phải có trước khi đẩy sang 1Office. Mở Sửa, chọn đủ 2 ô; nếu danh sách nhân sự trống thì admin phải gán mã 1Office trước (G42).',
          tags: ['duyệt', 'nhân sự', '1office'], related: ['G26', 'G42'],
        },
        {
          id: 'Q09', title: 'Chọn "Nhượng quyền + Liên kết" sao form lạ hẳn?',
          text: 'Đó là thiết kế: mô hình NQ_LK bật thêm cụm tab lồng "Nhượng quyền và Liên kết" với bảng Chi phí. Điền đủ cả 2 tab — xem hướng dẫn chi tiết ở G39.',
          tags: ['nq_lk', 'tab'], related: ['G39'],
        },
      ],
    },
  ],
};
