-- 90: Phong ban + chuc vu users sang select options thu cong (docs/8/47 - Buoc 1)
-- department da co (3 options cu Ky thuat/Van hanh/Hanh chinh) -> thay bang 10 phong ban Excel
-- chuc_vu text trong -> select 16 chuc danh Excel
-- Ca 2 field da gan form 15/16 + view 7 -> khong doi cau truc form/view
-- Idempotent.

UPDATE field_definitions
SET type = 'select',
    options = '[{"value":"Ban Tổng Giám đốc","label":"Ban Tổng Giám đốc","color":"#7c3aed","borderRadius":"rounded"},{"value":"Kênh Nhà phân phối","label":"Kênh Nhà phân phối","color":"#2563eb","borderRadius":"rounded"},{"value":"Phòng Setup và Vận hành","label":"Phòng Setup và Vận hành","color":"#0891b2","borderRadius":"rounded"},{"value":"Back office","label":"Back office","color":"#64748b","borderRadius":"rounded"},{"value":"Trung tâm KD miền Bắc","label":"Trung tâm KD miền Bắc","color":"#16a34a","borderRadius":"rounded"},{"value":"Trung tâm KD miền Trung","label":"Trung tâm KD miền Trung","color":"#65a30d","borderRadius":"rounded"},{"value":"Trung tâm KD miền Nam","label":"Trung tâm KD miền Nam","color":"#ca8a04","borderRadius":"rounded"},{"value":"Phòng Chính sách và Phát triển dự án","label":"Phòng Chính sách và Phát triển dự án","color":"#0d9488","borderRadius":"rounded"},{"value":"Phòng Chiến lược KD","label":"Phòng Chiến lược KD","color":"#4f46e5","borderRadius":"rounded"},{"value":"Phòng Công nghệ và Quy hoạch","label":"Phòng Công nghệ và Quy hoạch","color":"#9333ea","borderRadius":"rounded"}]'
WHERE entity = 'users' AND `key` = 'department'
  AND (type <> 'select' OR JSON_LENGTH(options) <> 10);

UPDATE field_definitions
SET type = 'select',
    options = '[{"value":"Tổng Giám đốc","label":"Tổng Giám đốc","color":"#7c3aed","borderRadius":"rounded"},{"value":"Phó Tổng Giám đốc","label":"Phó Tổng Giám đốc","color":"#6d28d9","borderRadius":"rounded"},{"value":"Phó Tổng Giám đốc Quản lý và Phát triển Nhà phân phối","label":"Phó Tổng Giám đốc Quản lý và Phát triển Nhà phân phối","color":"#2563eb","borderRadius":"rounded"},{"value":"Trưởng phòng phụ trách kênh NPP","label":"Trưởng phòng phụ trách kênh NPP","color":"#0284c7","borderRadius":"rounded"},{"value":"Trưởng phòng Setup và Vận hành","label":"Trưởng phòng Setup và Vận hành","color":"#0891b2","borderRadius":"rounded"},{"value":"Admin","label":"Admin","color":"#64748b","borderRadius":"rounded"},{"value":"Trợ lý Tổng Giám đốc","label":"Trợ lý Tổng Giám đốc","color":"#475569","borderRadius":"rounded"},{"value":"Giám đốc Trung tâm Kinh doanh","label":"Giám đốc Trung tâm Kinh doanh","color":"#16a34a","borderRadius":"rounded"},{"value":"TP chính sách và phát triển dự án","label":"TP chính sách và phát triển dự án","color":"#0d9488","borderRadius":"rounded"},{"value":"Chuyên viên Chiến lược Kinh doanh","label":"Chuyên viên Chiến lược Kinh doanh","color":"#4f46e5","borderRadius":"rounded"},{"value":"Trưởng phòng Công nghệ và Quy hoạch","label":"Trưởng phòng Công nghệ và Quy hoạch","color":"#9333ea","borderRadius":"rounded"},{"value":"Chuyên viên Quy hoạch","label":"Chuyên viên Quy hoạch","color":"#a855f7","borderRadius":"rounded"},{"value":"Chuyên viên Kỹ thuật","label":"Chuyên viên Kỹ thuật","color":"#0891b2","borderRadius":"rounded"},{"value":"Giám đốc Khu vực","label":"Giám đốc Khu vực","color":"#22c55e","borderRadius":"rounded"},{"value":"Chuyên viên Công nghệ","label":"Chuyên viên Công nghệ","color":"#6366f1","borderRadius":"rounded"},{"value":"Chuyên viên Phát triển Dự án","label":"Chuyên viên Phát triển Dự án","color":"#0ea5e9","borderRadius":"rounded"}]'
WHERE entity = 'users' AND `key` = 'chuc_vu'
  AND (type <> 'select' OR JSON_LENGTH(options) <> 16);
