export const TILE_PROVIDERS = [
  {
    id: 'leaflet-osm',
    name: 'Leaflet + OpenStreetMap',
    type: 'free',
    auth_type: 'none',
    requires_key: false,
    has_cluster: true,
    cluster_method: 'plugin',
    tile_url: 'https://a.basemaps.cartocdn.com/light_all/{z}/{x}/{y}{r}.png',
    tile_url_template: 'https://a.basemaps.cartocdn.com/{style}/{z}/{x}/{y}{r}.png',
    tile_url_styles: [
      { value: 'light_all', label: 'Sáng' },
      { value: 'dark_all', label: 'Tối' },
      { value: 'rastertiles/voyager', label: 'Voyager' },
    ],
    style_url: '',
    attribution: '&copy; <a href="https://carto.com/">CARTO</a> &copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors',
    subdomains: 'a,b,c,d',
    api_key: '',
    description: 'Miễn phí, mã nguồn mở. CARTO CDN (OSM data). Tích hợp Leaflet.markercluster.',
  },
  {
    id: 'maplibre-osm',
    name: 'MapLibre GL JS + OSM',
    type: 'free',
    auth_type: 'none',
    requires_key: false,
    has_cluster: true,
    cluster_method: 'built-in',
    tile_url: '',
    tile_url_template: '',
    style_url: 'https://demotiles.maplibre.org/style.json',
    attribution: 'Trong style JSON',
    subdomains: '',
    api_key: '',
    description: 'Miễn phí, mã nguồn mở. Built-in cluster qua GeoJSON Source (cluster: true).',
  },
  {
    id: 'openlayers-osm',
    name: 'OpenLayers + OSM',
    type: 'free',
    auth_type: 'none',
    requires_key: false,
    has_cluster: true,
    cluster_method: 'built-in',
    tile_url: '',
    tile_url_template: '',
    style_url: '',
    attribution: 'Tự động từ OSM',
    subdomains: '',
    api_key: '',
    description: 'Miễn phí, mã nguồn mở. Built-in cluster qua ol.source.Cluster.',
  },
  {
    id: 'maplibre-self-hosted',
    name: 'MapLibre + Self-hosted Tiles',
    type: 'self-hosted',
    auth_type: 'none',
    requires_key: false,
    has_cluster: true,
    cluster_method: 'built-in',
    tile_url: 'http://{domain}/tiles/{z}/{x}/{y}.pbf',
    tile_url_template: '',
    style_url: 'http://{domain}/style.json',
    attribution: 'Cấu hình theo bản quyền dữ liệu tự host',
    subdomains: '',
    api_key: '',
    description: 'Tự host tile server. Built-in cluster qua GeoJSON Source.',
  },
  {
    id: 'leaflet-self-hosted',
    name: 'Leaflet + Self-hosted Tiles',
    type: 'self-hosted',
    auth_type: 'none',
    requires_key: false,
    has_cluster: true,
    cluster_method: 'plugin',
    tile_url: 'http://{domain}/tiles/{z}/{x}/{y}.png',
    tile_url_template: '',
    style_url: '',
    attribution: 'Cấu hình theo bản quyền dữ liệu tự host',
    subdomains: '',
    api_key: '',
    description: 'Tự host tile server. Tích hợp plugin Leaflet.markercluster.',
  },
  {
    id: 'mapbox',
    name: 'Mapbox GL JS',
    type: 'api',
    auth_type: 'token',
    requires_key: true,
    has_cluster: true,
    cluster_method: 'built-in',
    tile_url: '',
    tile_url_template: 'https://api.mapbox.com/styles/v1/{style}/tiles/256/{z}/{x}/{y}@2x?access_token={key}',
    tile_url_styles: [
      { value: 'mapbox/streets-v12', label: 'Streets' },
      { value: 'mapbox/outdoors-v12', label: 'Outdoors' },
      { value: 'mapbox/light-v11', label: 'Light' },
      { value: 'mapbox/dark-v11', label: 'Dark' },
      { value: 'mapbox/satellite-streets-v12', label: 'Satellite Streets' },
      { value: 'mapbox/navigation-day-v1', label: 'Navigation Day' },
      { value: 'mapbox/navigation-night-v1', label: 'Navigation Night' },
    ],
    style_url: 'mapbox://styles/mapbox/streets-v12',
    attribution: '&copy; Mapbox &copy; OpenStreetMap',
    subdomains: '',
    api_key: '',
    api_key_placeholder: 'pk.eyJ1...',
    description: 'Free tier / Trả phí. Access Token + Style URL. Built-in cluster.',
    style_options: [
      { value: 'mapbox/streets-v12', label: 'Streets' },
      { value: 'mapbox/outdoors-v12', label: 'Outdoors' },
      { value: 'mapbox/light-v11', label: 'Light' },
      { value: 'mapbox/dark-v11', label: 'Dark' },
      { value: 'mapbox/satellite-streets-v12', label: 'Satellite Streets' },
      { value: 'mapbox/navigation-day-v1', label: 'Navigation Day' },
      { value: 'mapbox/navigation-night-v1', label: 'Navigation Night' },
    ],
  },
  {
    id: 'google-maps',
    name: 'Google Maps Platform',
    type: 'api',
    auth_type: 'token',
    requires_key: true,
    has_cluster: true,
    cluster_method: 'library',
    tile_url: '',
    tile_url_template: 'https://maps.googleapis.com/maps/api/staticmap?center=14.0583,108.2772&zoom={z}&size=256x256&maptype={style}&key={key}',
    tile_url_styles: [
      { value: 'roadmap', label: 'Đường phố' },
      { value: 'satellite', label: 'Vệ tinh' },
      { value: 'terrain', label: 'Địa hình' },
      { value: 'hybrid', label: 'Kết hợp' },
    ],
    style_url: '',
    attribution: '&copy; Google',
    subdomains: '',
    api_key: '',
    api_key_placeholder: 'AIza...',
    description: 'Free tier / Trả phí. API Key + Map ID (tùy chọn). Dùng @googlemaps/markerclusterer.',
  },
  {
    id: 'here-maps',
    name: 'HERE Maps (HERE SDK/JS)',
    type: 'api',
    auth_type: 'token',
    requires_key: true,
    has_cluster: true,
    cluster_method: 'built-in',
    tile_url: '',
    tile_url_template: 'https://maps.hereapi.com/v3/base/mc/{z}/{x}/{y}/png?style={style}&apiKey={key}',
    tile_url_styles: [
      { value: 'explore.day', label: 'Explore Day' },
      { value: 'explore.night', label: 'Explore Night' },
      { value: 'explore.satellite.day', label: 'Satellite Day' },
      { value: 'explore.carnav.day', label: 'Carnav Day' },
      { value: 'explore.grey.day', label: 'Grey Day' },
      { value: 'explore.traffic.day', label: 'Traffic Day' },
      { value: 'explore.traffic.night', label: 'Traffic Night' },
    ],
    style_url: '',
    attribution: '&copy; HERE',
    subdomains: '',
    api_key: '',
    api_key_placeholder: 'YOUR_API_KEY',
    description: 'Free tier / Trả phí. API Key + Engine/Layer Config. Built-in H.clustering.Provider.',
    style_options: [
      { value: 'explore.day', label: 'Explore Day' },
      { value: 'explore.night', label: 'Explore Night' },
      { value: 'explore.satellite.day', label: 'Satellite Day' },
      { value: 'explore.carnav.day', label: 'Carnav Day' },
      { value: 'explore.grey.day', label: 'Grey Day' },
    ],
  },
  {
    id: 'tomtom-maps',
    name: 'TomTom Maps SDK',
    type: 'api',
    auth_type: 'token',
    requires_key: true,
    has_cluster: true,
    cluster_method: 'library',
    tile_url: '',
    tile_url_template: 'https://api.tomtom.com/map/1/tile/{style}/{z}/{x}/{y}.png?key={key}',
    tile_url_styles: [
      { value: 'main', label: 'Main' },
      { value: 'hybrid', label: 'Hybrid' },
      { value: 'satellite', label: 'Satellite' },
    ],
    style_url: 'tomtom://vector/style/main',
    attribution: '&copy; TomTom',
    subdomains: '',
    api_key: '',
    api_key_placeholder: 'YOUR_API_KEY',
    description: 'Free tier / Trả phí. API Key + Style URL (tùy chọn). Cluster qua thư viện hỗ trợ.',
    style_options: [
      { value: 'tomtom://vector/style/main', label: 'Main' },
      { value: 'tomtom://vector/style/hybrid', label: 'Hybrid' },
      { value: 'tomtom://vector/style/satellite', label: 'Satellite' },
    ],
  },
  {
    id: 'arcgis-js',
    name: 'ArcGIS Maps SDK for JS',
    type: 'api',
    auth_type: 'token',
    requires_key: true,
    has_cluster: true,
    cluster_method: 'built-in',
    tile_url: '',
    tile_url_template: 'https://server.arcgisonline.com/ArcGIS/rest/services/{style}/MapServer/tile/{z}/{y}/{x}',
    tile_url_styles: [
      { value: 'World_Street_Map', label: 'Streets' },
      { value: 'World_Topo_Map', label: 'Topographic' },
      { value: 'World_Imagery', label: 'Satellite' },
      { value: 'World_Terrain_Base', label: 'Terrain' },
      { value: 'Dark_Gray_Base', label: 'Dark Gray' },
      { value: 'Light_Gray_Base', label: 'Light Gray' },
      { value: 'World_Reference_Overlay', label: 'Reference Overlay' },
    ],
    style_url: 'arcgis/topographic',
    attribution: '&copy; Esri',
    subdomains: '',
    api_key: '',
    api_key_placeholder: 'YOUR_API_KEY',
    description: 'Free tier / Trả phí. API Key qua esriConfig.apiKey. Built-in FeatureLayer.featureReduction.',
    style_options: [
      { value: 'arcgis/topographic', label: 'Topographic' },
      { value: 'arcgis/streets', label: 'Streets' },
      { value: 'arcgis/navigation', label: 'Navigation' },
      { value: 'arcgis/satellite', label: 'Satellite' },
      { value: 'arcgis/imagery', label: 'Imagery' },
      { value: 'arcgis/dark-gray', label: 'Dark Gray' },
      { value: 'arcgis/light-gray', label: 'Light Gray' },
    ],
  },
];

export const TILE_CATEGORIES = [
  { id: 'free', label: 'Miễn phí', description: 'Mã nguồn mở, không cần API key' },
  { id: 'self-hosted', label: 'Tự host', description: 'Tự cung cấp tile server' },
  { id: 'api', label: 'Dịch vụ API', description: 'Cần API key / Token' },
];

export const AUTH_TYPES = [
  { id: 'none', label: 'Không cần xác thực', icon: '🔓' },
  { id: 'token', label: 'API Key / Token', icon: '🔑' },
];

export function getProviderById(id) {
  return TILE_PROVIDERS.find(p => p.id === id);
}

export function getProvidersByType(type) {
  return TILE_PROVIDERS.filter(p => p.type === type);
}

export function getFreeProviders() {
  return TILE_PROVIDERS.filter(p => p.type === 'free');
}

export function getApiProviders() {
  return TILE_PROVIDERS.filter(p => p.type === 'api');
}
